/*
 * File: app/view/MyContainer.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyContainer', {
    extend: 'Ext.container.Container',

    id: 'studentContainer',
    layout: {
        align: 'stretch',
        type: 'hbox'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    flex: 1,
                    layout: {
                        type: 'fit'
                    },
                    items: [
                        {
                            xtype: 'treepanel',
                            id: 'classTree',
                            title: 'Classes',
                            store: 'ClassTreeStore',
                            viewConfig: {

                            }
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 3,
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            layout: {
                                type: 'fit'
                            },
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    id: 'studentDataGrid',
                                    title: 'Students Data',
                                    store: 'ClassJsonStore',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            maxWidth: 90,
                                            minWidth: 70,
                                            width: 90,
                                            align: 'center',
                                            dataIndex: 'Roll_No',
                                            text: 'Roll No'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            maxWidth: 300,
                                            minWidth: 300,
                                            width: 300,
                                            dataIndex: 'string',
                                            text: 'Name',
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    maxWidth: 150,
                                                    minWidth: 150,
                                                    width: 150,
                                                    dataIndex: 'FName',
                                                    text: 'First Name'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    maxWidth: 150,
                                                    minWidth: 150,
                                                    width: 150,
                                                    dataIndex: 'LName',
                                                    text: 'Last Name'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            maxWidth: 120,
                                            minWidth: 120,
                                            width: 120,
                                            align: 'center',
                                            dataIndex: 'Tel_No',
                                            text: 'Telephone Number'
                                        },
                                        {
                                            xtype: 'datecolumn',
                                            maxWidth: 120,
                                            minWidth: 120,
                                            width: 120,
                                            align: 'center',
                                            dataIndex: 'DOB',
                                            text: 'Date Of Birth'
                                        },
                                        {
                                            xtype: 'datecolumn',
                                            maxWidth: 120,
                                            minWidth: 120,
                                            width: 120,
                                            align: 'center',
                                            dataIndex: 'DOA',
                                            text: 'Date Of Admission'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            maxWidth: 120,
                                            minWidth: 120,
                                            width: 120,
                                            dataIndex: 'Address',
                                            text: 'Address'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            maxWidth: 120,
                                            minWidth: 120,
                                            width: 120,
                                            align: 'center',
                                            dataIndex: 'Pin_Code',
                                            text: 'Pin Code'
                                        }
                                    ],
                                    selModel: Ext.create('Ext.selection.RowModel', {

                                    })
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            layout: {
                                type: 'fit'
                            },
                            items: [
                                {
                                    xtype: 'form',
                                    id: 'frmStudentDetails',
                                    layout: {
                                        align: 'stretch',
                                        type: 'hbox'
                                    },
                                    bodyPadding: 10,
                                    title: 'Student Details',
                                    items: [
                                        {
                                            xtype: 'fieldset',
                                            flex: 1,
                                            padding: 20,
                                            title: 'Personal',
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    anchor: '100%',
                                                    fieldLabel: 'First Name',
                                                    name: 'FName',
                                                    readOnly: true
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    anchor: '100%',
                                                    fieldLabel: 'Last Name',
                                                    name: 'LName',
                                                    readOnly: true
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    anchor: '100%',
                                                    fieldLabel: 'Telephone Number',
                                                    name: 'Tel_No',
                                                    readOnly: true
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    anchor: '100%',
                                                    fieldLabel: 'Date Of Birth',
                                                    name: 'DOB',
                                                    readOnly: true
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    anchor: '100%',
                                                    fieldLabel: 'Address',
                                                    name: 'Address',
                                                    readOnly: true
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    anchor: '100%',
                                                    fieldLabel: 'Pin Code',
                                                    name: 'Pin_Code',
                                                    readOnly: true
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'fieldset',
                                            flex: 1,
                                            padding: 20,
                                            title: 'Office Use',
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    anchor: '100%',
                                                    fieldLabel: 'Roll No',
                                                    name: 'Roll_No',
                                                    readOnly: true
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    anchor: '100%',
                                                    fieldLabel: 'Date Of Admission',
                                                    name: 'DOA',
                                                    readOnly: true
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});